# Generated by Django 6.0.4 on 2026-05-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(unique=True)),
                ('language', models.CharField(default='ta', max_length=10)),
                ('audio_file', models.FileField(upload_to='tts_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
