# Generated by Django 6.0.4 on 2026-06-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttscache',
            name='article_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='ttscache',
            unique_together={('article_id', 'language')},
        ),
    ]
